### PR TITLE
:bug: Fix agent node affinity settings to always prefer control plane nodes

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [x] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by richardcase** [comment]
I think we need to hold off on this change for the following reasons:

- We've not seen any issues in our testing specifically related to the scheduling/placement of the agent pod(s). 
- We don't have time to thoroughly test the impact of this before the release
- We should consider fixing this upstream instead

**Comment by richardcase** [comment]
Lets split out the helm addon and changing the tests to use calico instead of kindnet.

**Comment by furkatgofurov7** [comment]
@Danil-Grigorev let's break this PR into two, the one with the changes @richardcase suggested and the latter we can go through in more detail.

**Comment by Danil-Grigorev** [comment]
I’ll close this PR and open a separate one with calico changes only later.

**Pull request closed without merging**
