### PR TITLE
🌱 Use calico as alternative to kindnet in e2e tests, and start testing helm chart proxy

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:
This PR provides alternative to kindnet network setup with calico. In my environment it is needed to make the local tests pass.

Additionally this introduces tests for helm addon provider as means for installing Calico CNI in the child cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Review by alexander-demicev — APPROVED** [review]
approved, I like that we will include CAPI addon providers in tests, @Danil-Grigorev please fix the conflict

**Comment by salasberryfin** [comment]
@Danil-Grigorev looks like this needs a rebase. Just out of curiosity, do you still need this change to run the test suite locally after changing the CIDR block to potentially avoid collisions?

**Comment by Danil-Grigorev** [comment]
I think this can be closed now. Remaining functionality of this PR is superseded by #654

**Comment by Danil-Grigorev** [comment]
I think this can be closed now. Remaining functionality of this PR is superseded by #654

**Pull request closed without merging**
