### PR TITLE
🌱 Downgrade CAPI to 1.4.6

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:
Due to rancher 2.8.3 still using 1.4.6 CAPI version, we will use this by default too.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
How about other provider versions in the file, i.e CAPA v2.3.5 [uses](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v2.3.5/go.mod#L45) CAPI v1.5.3, should they all also be updated to versions which uses v1.4.X version of CAPI?

**Review by richardcase — DISMISSED** [review]

**Comment by richardcase** [comment]
> How about other provider versions in the file, i.e CAPA v2.3.5 [uses](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v2.3.5/go.mod#L45) CAPI v1.5.3, should they all also be updated to versions which uses v1.4.X version of CAPI?

I think it should be ok as its based on the api contract. But i will check something quickly....

**Comment by richardcase** [comment]
Doing:

```bash
clusterctl init --core cluster-api:v1.4.6 -i aws
```

Results in CAPA **v2.4.1** being installed

**Comment by Danil-Grigorev** [comment]
Should we upgrade it then? :)

**Comment by furkatgofurov7** [comment]
> Doing:
> 
> ```shell
> clusterctl init --core cluster-api:v1.4.6 -i aws
> ```
> 
> Results in CAPA **v2.4.1** being installed

That is expected to fetch the latest patch if not specified? My point was how provider version which does not support the CAPI version can be installed together )

**Comment by Danil-Grigorev** [comment]
We were testing these versions in our CI with CAPI 1.4.6. Current set of defaults is safe from this perspective.

**Comment by richardcase** [comment]
> We were testing these versions in our CI with CAPI 1.4.6. Current set of defaults is safe from this perspective.

I agree. We have tested these combinations. Also the API version are the same.

**Review by furkatgofurov7 — APPROVED** [review]

**Review by richardcase — APPROVED** [review]

**Pull request merged**
