### PR TITLE
test: check migration to v3 controller

### PR DESCRIPTION
**Pull request by salasberryfin**
**What this PR does / why we need it**:

We decided to split into a separate PR the E2E tests added to validate v1 to v3 controller migration. The changes to the controller can be found in https://github.com/rancher/turtles/pull/575. This PR only affects E2E scenarios.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@salasberryfin can we rebase this PR?

**Comment by Danil-Grigorev** [comment]
@salasberryfin Can you please rebase this PR?

**Review by alexander-demicev — DISMISSED** [review]

**Comment by furkatgofurov7** [comment]
Does this need a rebase again?

**Comment by salasberryfin** [comment]
This was rebased today but it is still failing when trying to connect to the downstream cluster after migration using kubeconfig. Still figuring out the reason behind this.

**Comment by Danil-Grigorev** [comment]
@salasberryfin The problem you are facing might be fixed by https://github.com/rancher/turtles/commit/7653a8182ee99e9fbdf7c36c417b4331eeac3bd7#diff-7be87c7e06c4b33e0c43cce272e500934fca8631072faf36237af336d4c1c562R185-R190

**Pull request closed without merging**
